### ISSUE TITLE
cant find supercollider installation

### ISSUE THREAD

**Issue by cdbzb** [htor/sc-editor#11]
getting an error on Catalina "have you installed Supercollider in a non-standard location?"

I have a Supercollider.app in /Applications - there maybe some symlinking around with other locations - any ideas? thx

**Comment by htor** [comment]
ah, you have it installed under `/Applications/SuperCollider.app`? i think the editor assumes `/Applications/SuperCollider/SuperCollider.app` if i'm not mistaken.

**Comment by htor** [comment]
fixed in latest download v1.0.2.
