### ISSUE TITLE
Lookup word under cursor not working - Windows 10

### ISSUE THREAD

**Issue by fmiramar** [htor/sc-editor#9]
Windows 10
SuperCollider 3.11.1

The lookup word under cursor not working (ctrl + d).

**Comment by htor** [comment]
thanks. i made a fix for it. are you able to build the branch with the pr and test if it fixes it, or should i send you a new .exe to test with?

cheers

**Comment by htor** [comment]
the new release contains fix: https://github.com/htor/hadron-editor/releases/download/v1.0.2/Hadron-1.0.2.exe
